package com.jsdroid.uiautomator2.event;

public enum EventType {
    TYPE_VIEW_CLICKED,
    TYPE_VIEW_LONG_CLICKED,
    TYPE_VIEW_SELECTED,
    TYPE_VIEW_FOCUSED,
    TYPE_VIEW_TEXT_CHANGED,
    TYPE_WINDOW_STATE_CHANGED,
    TYPE_NOTIFICATION_STATE_CHANGED,
    TYPE_VIEW_HOVER_ENTER,
    TYPE_VIEW_HOVER_EXIT,
    TYPE_TOUCH_EXPLORATION_GESTURE_START,
    TYPE_TOUCH_EXPLORATION_GESTURE_END,
    TYPE_WINDOW_CONTENT_CHANGED,
    TYPE_VIEW_SCROLLED,
    TYPE_VIEW_TEXT_SELECTION_CHANGED,
    TYPE_ANNOUNCEMENT,
    TYPE_VIEW_ACCESSIBILITY_FOCUSED,
    TYPE_VIEW_ACCESSIBILITY_FOCUS_CLEARED,
    TYPE_VIEW_TEXT_TRAVERSED_AT_MOVEMENT_GRANULARITY,
    TYPE_GESTURE_DETECTION_START,
    TYPE_GESTURE_DETECTION_END,
    TYPE_TOUCH_INTERACTION_START,
    TYPE_TOUCH_INTERACTION_END,
    TYPE_WINDOWS_CHANGED,
    TYPE_VIEW_CONTEXT_CLICKED,
    TYPE_ASSIST_READING_CONTEXT
}
